import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './ui/globals.css'
import { Providers } from './providers';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Golgoths 13',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <body className={inter.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
